### ISSUE TITLE
Ambition 

### ISSUE THREAD

**Issue by pam-mightyminds** [mighty-minds/issues#32]
**Is your feature request related to a problem? Please describe.**
Having the dropdown button for the ambition will be a hassle for MM if ambition is not listed 

**Describe the solution you'd like**
Instead of dropdown, let organizations type the ambitions. Instructions for this part is included in the partner's kit. 

**Describe alternatives you've considered**

**Additional context**
![Screen Shot 2021-03-09 at 3 09 37 PM](https://user-images.githubusercontent.com/76203496/110432236-d12c2a80-80e9-11eb-904c-9519d93a87a5.png)

**Comment by pam-mightyminds** [comment]
Instead of dropdown option, can we just remove the options to choose from and jet let organizations type the ambitions? There are so many ambitions and im sure we wont be able to put all in the options. It will be. hassle for both parties if orgs will ask us to add ambitions just to cater to their students. For example, one ogranization requested the following to be added: medical technologist, respiratory therapist, cruise ship attendant. Instead of adding these option, lets just switch from allowing them to type each students ambition without needing the dropdown button for the ambitions.

**Comment by jofftiquez** [comment]
Hello @pam-mightyminds I will double check in the backend if this can be an arbitrary field. If yes, we can maybe convert this to a combination of free text + list, so that if the ambition that they want to add is already there they can just pick it. What do you think?

**Comment by pam-mightyminds** [comment]
@jofftiquez im okay with this. For now, can we add the following in the list since an org is waiting for these before publishing 3 students: medical technologist, respiratory therapist, cruise ship attendant

**Comment by jofftiquez** [comment]
Noted. @pam-mightyminds. Those 3 were already added in the last update.
