### ISSUE TITLE
Change target fund - CaVolun Initiative

### ISSUE THREAD

**Issue by pam-mightyminds** [mighty-minds/issues#34]
Make the target funds of each CaVolun Initiative scholars to 15, 000 PHP.

**Comment by jofftiquez** [comment]
This is done. Thanks.

**Comment by pam-mightyminds** [comment]
Change to 15, 000 PHP

[Screen Shot 2021-03-16 at 12 38 46 PM](https://user-images.githubusercontent.com/76203496/111263685-37bcc580-8661-11eb-9c7b-487994beeba8.png)

**Comment by jofftiquez** [comment]
Hi @pam-mightyminds I adjusted the funding for Merwin

![image](https://user-images.githubusercontent.com/8638243/111281168-9b51ed80-8677-11eb-8721-78de9564d908.png)
