### ISSUE TITLE
Volunteer Page- Content

### ISSUE THREAD

**Issue by pam-mightyminds** [mighty-minds/issues#8]
Update content: 

Currently, Mighty Minds is run by volunteers. Its operational costs are solely funded by the founders. 

![Screen Shot 2020-12-22 at 4 04 48 PM](https://user-images.githubusercontent.com/76203496/102864704-8f3b0300-446f-11eb-9dc3-31eb02f87fe4.png)

**Comment by Prototype1001** [comment]
Hello. Anything else on this ticket?

**Comment by jofftiquez** [comment]
@pam-mightyminds shall we close this already? Thanks

**Comment by pam-mightyminds** [comment]
Im okay with this one

**Comment by jofftiquez** [comment]
Thanks @pam-mightyminds
